name = "MarginalTreatmentEffectsWithMultipleInstruments"
uuid = "e8ccf7cf-21b5-4ee4-a618-165bb004bb9c"
authors = ["A. Torgovitsky <atorgovitsky@gmail.com>"]
version = "0.1.0"

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
Clp = "e2554f3b-3117-50c0-817c-e040a3ddf72d"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
NamedArrays = "86f7a689-2022-50b4-a561-43c23ac3c673"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
Suppressor = "fd094767-a336-5f1f-9728-57cf17d0bbfb"
